<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutPutPath>../build</OutPutPath>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>E:\work\programs\desktop\AvionPlot\src\Assets\Img\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>

</Project>
